[project]
name = "tmp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyyaml",
]

[tool.uv.sources]
pyyaml = { git = "https://github.com/yaml/pyyaml", rev = "6.0.3" }
