name: uv cache CI

on:
  push:
  workflow_dispatch:
jobs:
  init:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Get cache suffix
        if: ${{ runner.os == 'Linux' }}
        id: cache-suffix
        run: |
          $(gcc --print-file-name=libc.so.6) | \
            awk 'NR==1 {print "CACHE_SUFFIX=glibc-" $NF}' >> "$GITHUB_OUTPUT"
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: ${{ steps.cache-suffix.outputs.CACHE_SUFFIX }}
      - name: Build and Install pyyaml
        run: |
          uv cache prune
          uv sync -vv

  test:
    needs: init
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Build and Install pyyaml
        run: |
          uv sync -vv
      - name: Run Test
        run: |
          uv run python -c "import pyworld"
